version: '3.8'

services:
  app:
    build: .
    container_name: invoice-reimbursement-system
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped 