name: Run FastAPI Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pytest
          pip install --upgrade fastapi starlette

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # If using a custom OpenAI-compatible endpoint:
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}  # Optional
          PYTHONPATH: .
        run: |
          pytest --maxfail=1 --disable-warnings -v
